rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head
jobs:
  allow_failures:
  - rvm: ruby-head
before_script:
  - sh bootstrap
  - ruby extconf.rb
  - make
script: "export LD_LIBRARY_PATH=`rvm config-get libdir`:$LD_LIBRARY_PATH && rake"
branches:
  only:
    - master
