environment:
  matrix:
    - RUBY_VERSION: "26-x64"

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install

build: off

before_build:
  - ruby -v
  - gem -v
  - bundle -v

build_script:
  - ridk enable
  - ruby extconf.rb
  - make

test_script:
  - bundle exec rake test
