name: Rice CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-on-nix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Configure
      run: ruby extconf.rb
    - name: Build
      run: make all
    - name: Tests
      run: bundle exec rake test

  test-on-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: brew install autoconf automake
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Configure
      run: ruby extconf.rb
    - name: Build
      run: make all
    - name: Tests
      run: bundle exec rake test

  test-on-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, head] # '3' explicitly is not yet released for windows. https://github.com/ruby/setup-ruby/issues/134
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Configure
      run: ruby extconf.rb
    - name: Build
      run: make all
    - name: Tests
      run: bundle exec rake test
