name: Rice CI

on:
  push:
    branches: [ debug ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        ruby: ['3.0']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Configure
      run: rake headers
    - name: Build
      run: rake build
    - name: Test
      run: rake test
